# Generated by Django 2.1.7 on 2019-04-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pitt_wall'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
